### ISSUE TITLE
How to do routing from js file

### ISSUE THREAD

**Issue by lokeshpatchala** [chandrakiran-dev/lwc-router#5]
Iam having a requirement on button click I need to navigate to different component and I want to do it from js file I went through the documentation I didn't find any example on how to do it  from js file Please can any one help me on this thanks in advance

**Comment by chandrakiran-dev** [comment]
Hi @lokeshpatchala,

As I can understand, you are trying to navigate to route from the button click. Below are the code for the navigation.

```
/**
* Handle for the button click
*/
handleButtonClick(){
      this.changeRoute('/about');
}

/**
* This method will navigate to the given path
*/
changeRoute(path){
      window.location.replace( window.location.origin + window.location.pathname + '#' +  path);
}

```
 
You can also move `changeRoute` method to your utility and use this wherever you want.

Hope this will works for you.

Thank you for raising this one, we will update the documentation for this.
